### ISSUE TITLE
False positive: banggood.com

### ISSUE THREAD

**Issue by amano-kenji** [stonecrusher/filterlists-pihole#2]
It is a popular ecommerce website.

**Comment by stonecrusher** [comment]
Well I don't create the content of the list, it's just taken from  https://www.watchlist-internet.at/

They say "verified and added on 14.10.2022"
https://www.watchlist-internet.at/liste-problematischer-shops/shops/debanggoodcom/

>Wer hier bestellt, erhält minderwertige Ware, muss mit langen Lieferzeiten, zusätzlichen Kosten und mit Problemen bei Retouren rechnen. 

But I think you're right, I'll whitelist it. It's a well known aliexpress alternative and 95% of people ordering there are aware of the risks.

https://github.com/stonecrusher/filterlists-pihole/commit/c1f41d240cc73e26d29ea82d0edc015a55086aa4
